- view-template:
    name: 'configure'
    description: 'jobs that reconfigure resources in place'
    view-type: list
    regex: '(^configure|^reconfigure|^set)-.*'

- project:
    name: 'configure-view'
    views:
        - 'configure'
    seq:
        - a
        - b
        - c
